title: Erkam Tuna Bayoğlu
url: "http://erkamtb.tech"
baseurl: "/resume"

markdown: kramdown
#ins_logo: #"./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, Edited By erkamtb"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/resume/"
 - name: "My Projects"
   link: "/resume/projects/projects" 
 - name: "Resume"
   link: "/resume/cv"
 - name: "Contact"
   link: "/resume/contact"