title: Erkam Tuna Bayoğlu
url: "https://erkamtb.github.io"
baseurl: "/researcher"

markdown: kramdown
ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana Edited By erkamtb"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "My Projects"
   link: "/projects" 
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
